#! /bin/sh

### BEGIN INIT INFO
# Provides:          i2c-rtc-ds1307
# Required-Start:    $local_fs mountdevsubfs
# Required-Stop:     $local_fs
# X-Start-Before:    ntp
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Init I2C RTC DS1307 and set clock
### END INIT INFO

# Author: Alexander Gordeyev <s0meuser@yandex.ru>

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="I2C RTC DS1307"
NAME=i2c-rtc-ds1307
SCRIPTNAME=/etc/init.d/$NAME

[ -x /sbin/hwclock ] || exit 0
[ -x /usr/sbin/i2cdetect ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

get_state()
{
	i2cdetect -y 1 | awk '/^60: / {print $10}'
}

#
# Function that starts the daemon/service
#
do_start()
{
	if [ "$(get_state)" = 68 ]; then
		echo ds1307 0x68 >/sys/class/i2c-adapter/i2c-1/new_device
	fi
	test "$(get_state)" = UU || return 2
	hwclock -s || return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
	test "$(get_state)" = UU || return 2
	hwclock -w || return 2
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
	test "$(get_state)" = UU && exit 0 || exit 1
	;;
  *)
	echo "Usage: $SCRIPTNAME start|stop|status" >&2
	exit 3
	;;
esac

:
